name: staging
url: https://serialforbreakfast.github.io/TooScaryDidntStream/staging/pr-{PR_NUMBER}/
protection_rules:
  - required_reviewers:
      users: []
      teams: []
    required_status_checks:
      strict: false
      contexts: []
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false
    required_conversation_resolution: false
